ALTER TABLE public.chatbot_settings
  ADD COLUMN IF NOT EXISTS avatar_size INTEGER NOT NULL DEFAULT 64,
  ADD COLUMN IF NOT EXISTS outline_color TEXT NOT NULL DEFAULT '#10b981',
  ADD COLUMN IF NOT EXISTS bounce_enabled BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS bounce_duration_s NUMERIC NOT NULL DEFAULT 3,
  ADD COLUMN IF NOT EXISTS ping_enabled BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS ping_duration_s NUMERIC NOT NULL DEFAULT 2.5;